#!perl

# Extract linear recurrence signatures from jcat25 grep
# @(#) $Id$
# 2026-02-03: copied from ../lrindex
# 2019-02-22: tables 'lrindx' and 'lrlink'
# 2019-02-19, Georg Fischer
#
#:# Usage:
#:#   perl extract_signat.pl -c > signat.create.sql
#:#   perl extract_signat.pl [-d debug] lrlink1.tmp > signat.txt
#:#      -d  mode 0=none, 1=some, 2=more
#--------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d:%02d"
        , $year + 1900, $mon + 1, $mday, $hour, $min, $sec);

my $debug = 0;
if (scalar(@ARGV) == 0) {
    print `grep -E "^#:#" $0 | cut -b3-`;
    exit;
}
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{c}) {
        &create_sql();
        exit(0);
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

#----
my ($line, $aseqno, $type25, $sigord, $longord, $wordord, $signature, $keyword);
my $nok = "";
# INSERT the creation time
$aseqno  = "A000000";
$type25  = "#";
$sigord  = -1;
$longord = "";
$wordord = "";
$signature = $timestamp;
$keyword = "";
my @elems; # terms in the signature
&output();

while (<>) {
    s/\s+\Z//; # chompr
    $line = $_;
    $keyword = "";
    $nok     = "";
    $signature = "?sig0";
    if (0) {
    #                    1 1  2        2              3   3                       4      4
    } elsif ($line =~ m{^(.)H ([A-Z]\d+)[^\#]+\#order_(\d+)[^\,]+\, *signature *\(([^\)]+)}) {
        $type25    = $1;
        $aseqno    = $2;
        $longord   = $3;
        $signature = $4 || "?sig1";
#       $signature = "\"$signature\"";
        $longord   =~ s{\A0+}{};
        $wordord   = $longord;
        if ($line =~ m{\, order *(\d+)}) {
            $wordord = $1;
        } 
#       $keyword    .= ",match1";
    #                    1 1  2        2              3   3                 4   4
    } elsif ($line =~ m{^(.)H ([A-Z]\d+)[^\#]+\#order_(\d+)[^\,]+\, *order *(\d+)}) {
        $type25    = $1;
        $aseqno    = $2;
        $longord   = $3;
        $longord   =~ s{\A0+}{};
        $wordord   = $longord;
        $keyword  .= ",nosig"
    #                    1 1  2                                3      3
    } elsif ($line =~ m{^(.)H ([A-Z]\d+)[^\,]+\, *signature *\(([^\)]+)\)}) {
        $type25    = $1;
        $aseqno    = $2;
        $signature = $3 || "?sig3";
        $longord   = "0";
        $wordord   = $longord;
#       $keyword    .= ",match3";
    } else {
        $nok = "nomatch";
    }
    if ($nok eq "") {
        $signature =~ s{[ \{\}\(\)]}{}g;
        @elems = split(/\,/, $signature);
        my $elemord  = scalar(@elems);
        if ($longord eq "0") {
            $longord = scalar(@elems);
            $sigord  = $longord;
            $wordord = $longord;
        }
        if (length($longord) > 2) { # max order = 100
            $sigord = -1;
            $signature = "?sig4";
            $wordord = $sigord;
        } else {
            $sigord = $longord;
            if (($signature !~ m{\A\?}) && $elemord ne $sigord) {
                $nok = "order " . scalar(@elems) . "<>$sigord"; # , " . join(",", @elems);
            }
            if ($wordord ne $sigord) {
                $nok = "wordord $wordord<>$sigord";
            }
        }
    }
    &output();
} # while <>
# end main
#----------
sub output {
    $keyword =~ s{^\,}{}; # remove leading comma
    if ($nok eq "") {
        print join("\t"
            , $aseqno
            , $type25
            , $sigord
            , $longord
            , $signature
            , $keyword
#           , $line
            ) . "\n";
    } else {
        print STDERR "$line -> $nok\n";
    }
} # output
#-----------------
sub create_sql {
    my ($tabname) = @_;
    if (0) {
    # A380292 order 6615344776548816157229109892561942561580100000 !??
    } elsif ($tabname eq "signat") {
        print <<"GFis";
--  OEIS-mat: $tabname - working table for signatures of linear recurrences
--  \@(#) \$Id\$
--  $timestamp, generated by extract_signat.pl - DO NOT EDIT HERE!
--
DROP    TABLE  IF EXISTS $tabname;
CREATE  TABLE            $tabname
    ( aseqno    VARCHAR(10)  NOT NULL -- A322469
    , type25    VARCHAR(4)            -- %H
    , sigord    INT                   -- number of signature elements, or -1 if longord too big
    , longord   VARCHAR(128)          -- original order from OEIS
    , signature VARCHAR(4096)         -- comma separated, without whitespace and "( )"
    , keyword   VARCHAR(64)           -- period, binom=7 etc.
    , PRIMARY KEY(aseqno)
    );
COMMIT;
GFis
    }
} # create_sql
#-------------------------------------------------
__DATA__
#H A199317 <a href="/index/Rec">Index entries for linear recurrences with constant coefficients</a>, signature (7,-6).
%H A216544 <a href="/index/Rec">Index entries for linear recurrences with constant coefficients</a>.

#H A385106 <a href="/index/Rec#order_04">Index entries for linear recurrences with constant coefficients</a>, signature (3,-3,1,1)
#H A385107 <a href="/index/Rec#order_05">Index entries for linear recurrences with constant coefficients</a>, signature (4,-6,4,-1,1).
#H A385121 <a href="/index/Rec#order_02">Index entries for linear recurrences with constant coefficients</a>, signature (12,-1).
#H A385142 <a href="/index/Rec#order_05">Index entries for linear recurrences with constant coefficients</a>, signature (4,-6,4,-1,1).
%H A385312 <a href="/index/Rec#order_08">Index entries for linear recurrences with constant coefficients</a>, signature (13,-72,222,-417,489,-350,140,-24).
#H A385396 <a href="/index/Rec#order_05">Index entries for linear recurrences with constant coefficients</a>, signature (1,0,0,2,-2).
%H A385407 <a href="/index/Rec#order_07">Index entries for linear recurrences with constant coefficients</a>, signature (7,-21,35,-35,21,-7,1).

%H A120466 <a href="/index/Rec#order_16">Index entries for linear recurrences with constant coefficients</a>, order 16, signature (11, 1370, 77929, 3643587, 60643963, 1886144770, 9489622853, 321733140518, -1184682856228, 17176558617832, -180204018965968, -1936508818801952, -5294214919102464, -11553018771853312, 548121408581582848, 1868826208968376320).

#H A385339 <a href="/index/Rec#order_29282">Index entries for linear recurrences with constant coefficients</a>, order 29282.
#H A385279 <a href="/index/Rec#order_31104">Index entries for linear recurrences with constant coefficients</a>, order 31104.
