#!perl

# A230549 Coins left after packing twin hearts patterns into n X n coins.
# 2019-05-24, Georg Fischer
# Same results as (MMA):
# LinearRecurrence[{0,1,1,0,-1,1,0,-1,-1,0,1},{4,5,8,13,12,21,32,33,40,57,48},mk1000]

use strict;
use integer;

my $limit = shift(@ARGV);
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min, $sec);
$timestamp = sprintf ("%04d-%02d-%02d", $year + 1900, $mon + 1, $mday);

my $col = 1;
my $row = 0;
my $n = 2;
print <<"GFis";
# A230549 Coins left after packing twin hearts patterns into n X n coins.
# Table of n, a(n) for n = 2..$limit;
# Generated by Georg Fischer with a230549.pl at $timestamp
GFis
while ($n <= $limit) {
  	my $add = 0;
  	if (($n % 2) * ($n % 3) != 0) {
    	$add = 1;
	}
  	if ($n >= 4 and $n % 2 == 0) {
    	$col ++;
	}
  	if ($n >= 3 and $n % 3 == 0) {	
    	$row ++;
	}
	my $term = $n * $n - ($col * $row + $add) * 4;
	print "$n $term\n";	
	$n ++;
} # while
print "\n\n";
