#!perl

# Cut multiple equations into several lines
# @(#) $Id$
# 2024-02-02, Georg Fischer
#
#:# Usage:
#:#   perl cuteqs.pl input.cat25 > output.seq4
#--------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min);
my $progname = $0;
print "# Generated by $progname at $timestamp\n";

my $debug = 0;
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my ($aseqno, $list1, $list2, $rest, $seq1, $seq2);
#while (<>) {
while (<DATA>) {
    s/\s+\Z//; # chompr
    my $line = $_; 
    if ($line =~ m{\A(A\d+) }) {
        $aseqno = $1;
        #                 1      1    2  2
        if ($line =~ m{giv(en|ing) by (.*)}) {
            my $oper = $2;
            $oper =~ tr/\[\]/\(\)/;
            if ($debug >= 1) {
            	print "aseqno=$aseqno, oper=$oper\n";
            }
            #               (1      1 )          (2      2 )3  3
            if ($oper =~ m{\(([^\)]+)\) *DELTA *\(([^\)]+)\)(.*)}) {
                ($list1, $list2, $rest) = ($1, $2, $3);
                $list1 =~ s{ }{}g;
                $list2 =~ s{ }{}g;
                $list1 =~ s{\, *\.+}{}g;
                $list2 =~ s{\, *\.+}{}g;
                $seq1 = "A000000";
                $seq2 = "A000000";
                print join("\t", $aseqno, "deldel", 0, "new $seq1()", "new $seq2()", "[$list1]", "[$list2]", $rest) . "\n";
            } else {
            	print "?? $oper\n";
            }
        } else {
            print STDERR "# $aseqno: no \"given by\" found: $line\n";
        }
    } # else ignore
} # while <>
__DATA__
A091977 Triangle, with zeros omitted, given by (1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, ...) DELTA (0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, ...) where DELTA is the operator defined in A084938. - _Philippe Deléham_, Feb 06 2012
A094344 Triangle T(n,k), 0<= k <= n, read by rows; given by [0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, ...] DELTA [1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, ...] where DELTA is the operator defined in A084938.
A094456 Triangle T(n,k), 0<=k<=n, read by rows; given by [0, 1, 0, 2, 0, 3, 0, 4, 0, 5, 0, ...] DELTA [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...] where DELTA is the operator defined in A084938.
A094665 Another version of triangular array in A083061: triangle T(n,k), 0<=k<=n, read by rows; given by [0, 1, 3, 6, 10, 15, 21, 28, ...] DELTA [1, 2, 3, 4, 5, 6, 7, 8, ...] where DELTA is the operator defined in A084938.
A098435 Essentially the same as the triangle giving by [0,-1,-1,-4,-4,-9,-9,-16,-16,-25,...] DELTA[1,0,1,0,1,0,1,0,1,0,...] = 1; 0,1; 0,-1,1; 0,2,-3,1; 0,-8,13,-6,1; 0,56,-92,45,-10,1; ... where DELTA is the operator defined in A084938. - _Philippe Deléham_, Aug 30 2006
A099394 Triangle given by [4,0,8,0,12,0,16,0,20,0,24,0,28,0,...] DELTA [1,1,2,2,3,3,4,4,5,5,6,6,...] where DELTA is the operator defined in A084938. - _Philippe Deléham_, Jun 04 2009
