#!perl

# Cut multiple equations into several lines
# @(#) $Id$
# 2024-04-12: not only for DirectSequence
# 2024-02-02, Georg Fischer
#
#:# Usage:
#:#   perl cuteqs.pl input.cat25 > output.seq4
#--------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min);
my $progname = $0;
print "# Generated by $progname at $timestamp\n";

my $debug = 0;
if (0 && scalar(@ARGV) == 0) {
    print `grep -E "^#:#" $0 | cut -b3-`;
    exit;
}
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

while (<>) {
    s/\s+\Z//; # chompr
    my $line = $_;
    print "# $line\n" if $debug >= 2;
    my ($type, $aseqno, $rest) = split(/ +/, $line, 3);
    next if ($rest =~ m{(Sum|Prod|exp|sin|cos|\.\.|\,)}i); # ignore "Sum_{", "Prod_", ".." etc.
    $rest =~ s{ *a\(n\) *\= *}{}; # remove "a(n) = "
    $rest =~ s{[\.\;\:].*}{};
    foreach my $eq1 (split(/ *\= */, $rest)) {
        print "# eq1=\"$eq1\", rest=\"$rest\"\n" if ($debug >= 1);
        if (0) {
        } elsif ($eq1 =~ m{A\d+\(n\)}) {
            if (0) {
            } elsif ($eq1 =~ m{\A\s*\Z}) { # ignore
            } elsif ($eq1 =~ m{€})       { # ignore
            } elsif ($eq1 =~ m{\AA\d+\(A\d+\(n\)\)}) {
                print        join("\t", $aseqno, "dirtraf", 0, "$eq1") ."\n";
        #   } elsif ($eq1 =~ m{\AA\d+\(A\d+\(n\)\)}) {
        #       print STDERR join("\t", $aseqno, "cut"   , 0, "$eq1") ."\n";
            } else {
                print        join("\t", $aseqno, "multraf", 0, "$eq1") ."\n";
            }
        }
    } # foreach
} # foreach $line
#--------------------------------------------
__DATA__
%N A325975 a(n) = gcd(A325977(n), A325978(n)).
%F A325975 a(n) = gcd(A325977(n), A325978(n)).
