#!perl

# Create wiki text Wikipedia link occurrences
# @(#) $Id$
# 2020-08-04, Georg Fischer
#
#:# Usage:
#:#   perl wikify [-d debug] infile > outfile
#--------------------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min, $sec);
$timestamp = sprintf ("%04d-%02d-%02d", $year + 1900, $mon + 1, $mday);
my $debug    = 0;

while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my $count = 0;
print "<!-- generated by Georg Fischer with OEIS-mat/wikipedia/wikify.pl at $timestamp -->\n";
while (<>) { # read inputfile
    s/\s+\Z//; # chompr
    s/\A\s+//; # remove leading spaces
    my $line = $_;
    $count ++;
    my ($occs, $link) = split(/\s+/, $line);
    $link =~ m{\/(A\d+)};
    my $aseqno = $1;
    print ($count == 1 ? "" : ", ");
    if ($count % 10 == 0) {
        print "\n";
    }
    print "$aseqno" . ($occs == 1 ? "" : " ($occs)");
} # while <>
print "\n";
#---------------------------------------
__DATA__
      1 https://oeis.org/A000001
      2 https://oeis.org/A000002
      1 https://oeis.org/A000012
     21 https://oeis.org/A000029
      6 https://oeis.org/A000032
      3 https://oeis.org/A000040
      6 https://oeis.org/A000041
      1 https://oeis.org/A000042
      3 https://oeis.org/A000043
