#!perl

# Generate an HTML working list from files *_change.txt with rotten links (%H lines)
# @(#) $Id$
# 2020-01-17: for finch3, with cat25 prefixes
# 2019-04-18, Georg Fischer: copied from ../common/html_checks.pl
#
#:# usage:
#:#   perl html_changes.pl [-init|-list|-term] [-m makefile] some_check.txt > some_check.html
#:#       -init write header  of index file
#:#       -term write trailer of index file
#:#       -list write table of sequences to be changed (default)
#:#       -m    take the comments form this makefile (default: changes.make, for -var only)
#:#---------------------------------
use strict;
use integer;
use warnings;

my $index_name = "changes_index.html";
my $make_name  = "changes.make";
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d"     # :%02d\+01:00"
        , $year + 1900, $mon + 1, $mday, $hour, $min);  # , $min, $sec, $isdst);
if (scalar(@ARGV) == 0) { # print help and exit
  print `grep -E "^#:#" $0 | cut -b3-`;
  exit;
} # print help
my $debug  = 1;
my $mode   = "list";
my @labels = ("A-Number", "Links");

while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A\-})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{(init)}) {
      $mode = $1;
    } elsif ($opt  =~ m{(term)}) {
      $mode = $1;
    } elsif ($opt  =~ m{(list)}) {
      $mode = $1;
    } elsif ($opt  =~ m{m}) {
        $make_name =  shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my $target = "Change";
my $title  = "Change";
my $infile = shift(@ARGV);
if ($infile =~ m{^(\w+_change)}) {
    $target = "$1:";
    $title = `grep -i $target $make_name`;
    $title =~ s{\s+\Z}{};
    $title =~ s{$target\s*\#\s*}{};
    $target =~ s{\W}{}g;
    # print $title;
}
my $count = 0;
#---------------
if (0) {
} elsif ($mode =~ m{init}   ) {
    print &get_html_head("Index of link change worksheets");
    print "<tr><th>No.</th><th class=\"bor\">Name</th>"
      . "<th class=\"bor\">Count</th>"
      . "<th class=\"bor\">Description</th></tr>\n";

} elsif ($mode =~ m{term}   ) {
    print &get_html_tail();
    
} elsif ($mode =~ m{list}   ) {
    my ($aseqno, $old_h, $new_h, $rep_link, $rep_h);
    print &get_html_head("Change Worksheet");
    open(INF, "<", $infile) or die "cannot read \"$infile\"\n";
    while (<INF>) {
        s/\s+\Z//; # chompr
        my $line = $_;
        if (0) { 
        } elsif ($line =~ m{^\#\s*(http.*)}) {
            $rep_link = $1;
            if ($debug >= 1) {
                    print STDERR "rep_link1 = \"$rep_link\"\n";
            }
        } elsif ($line =~ m{^\%H\s+(A\d+)\s+(.*)}) { # line to be replaced
            $count ++;
            $aseqno = $1;
            $old_h  = "\%H $2";
            $new_h  = $old_h;
            $new_h  =~ s{S\.\s*R\.\s*Finch}{Steven R. Finch}i;
            $new_h  =~ s{\s*[\[\(]\s*broken\s+link\s*[\]\)]\s*}{}i; # remove it
            $rep_h  = $new_h;
            $new_h .= " [Broken link]";
            if ($debug >= 2) {
                    print STDERR "rep_link2 = \"$rep_link\"\n";
            }
            $rep_h  =~ s{href\=\"[^\"]+\"}{href\=\"$rep_link\"};
            if ($rep_link =~ m{web\.archive\.org}) {
                $rep_h .= " [From the Wayback machine]";
            }
            print <<"GFis";
    <tr><td>$count</td><td class=\"bor bott\"><a href=\"https://oeis.org/edit\?seq=$aseqno\&internal=1\" target=\"_blank\">$aseqno</a></td>
        <td class=\"bor\"><!--<textarea readonly wrap="hard" rows="4" cols="160">$new_h
$rep_h
</textarea><br />-->$old_h</td></tr>
GFis
        } else {
            $rep_link = "#################";
        }
    } # while <INF>
    close(INF);
} else { 
    die "invalid mode \"$mode\"\n";
}
#---------------
if ($mode !~ m{init|term}) {
    open(IDX, ">>", $index_name) or die "cannot append to \"$index_name\"\n";
    print IDX "<tr><td class=\"bor\"><a href=\"$target.html\">$target</a></td>"
        . "<td class=\"bor\" align=\"right\">$count</td>"
        . "<td class=\"bor\">$title</td></tr>\n";
    print STDERR sprintf("%-16s %6d  %-64s\n", $target, $count, $title);
    close(IDX);
    print get_html_tail();
}
#-----------------------------
sub get_html_tail {
    my $result = <<"GFis";
</table>
<p>
GFis
    if ($mode !~ m{init|term}) {
        $result .= "$count sequences to be changed\n";
    }
    $result .= <<"GFis";
<br />Generated by <a href="https://github.com/gfis/OEIS-mat/blob/master/broken_link/html_changes.pl">html_changes.pl</a>: $timestamp 
<br />Questions, suggestions: email <a href="mailto:georg.fischer\@t-online.de">Georg Fischer</a>
</p>
</body>
</html>
GFis
} # get_html_tail
#-----------------------------
sub get_html_head {
    my ($title) = @_;
    return <<"GFis";
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" [
]>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>$target</title>
<meta name="generator" content="https://github.com/gfis/OEIS-mat/blob/master/broken_link/html_changes.pl" />
<meta name="author"    content="Georg Fischer" />
<style>
body,table,p,td,th
        { font-family: Verdana,Arial,sans-serif; }
table   { border-collapse: collapse; }
td      { padding-right: 4px; }
tr,td,th{ vertical-align: top; }
th      { text-align: left; }
.arr    { text-align: right; background-color: white; color: black; }
.bor    { border-left  : 1px solid gray    ; padding-left: 8px; padding-right: 8px; 
          border-top   : 1px solid gray    ;
          border-right : 1px solid gray    ;                                
          border-bottom: 1px solid gray    ;  }
.bott   { vertical-align: bottom; }
.refp   { background-color: lightgreen;    } /* refers to the partner */
.warn   { background-color: yellow;        } /* no reference to the partner and newer */
.comt   { background-color: peachpuff;     } /* lightpink; #fff0f0; a lightred like in history, for conclusion */
.err    { background-color: red; color: white; } /* for errors */
.refn   { background-color: greenyellow;   } /* no reference to the partner */
.more   { color:white  ; background-color: blue;      }
.dead   { color:white  ; background-color: gray;      }
.fini   { color:black  ; background-color: turquoise; }
.narrow { font-size    : smaller;  }
.prefor { font-family  : monospace; white-space: pre;
          font-size    : large; font-weight: bold; }
.same   { background-color:lightyellow }
</style>
</head>
<body>
<h3><a href="change_index.html" target="_blank">OEIS-mat</a> - $target</h3>
<h4>$title</h4>
<table class="bor">
GFis
} # get_html_head
__DATA__
# http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=0439F4E4BEF7D53D86C95CD41A7B281F?doi=10.1.1.638.5547&rep=rep1&type=pdf
%H A160498 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/">Cubic and quartic characters</a>
%H A114643 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/">Cubic and quartic characters</a>.
%H A160499 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/">Cubic and quartic characters</a>.

# http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.299.1204&rep=rep1&type=pdf
%H A110563 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/">Elliptic curves over Q</a>

# https://oeis.org/A241121/a241121.pdf
%H A054909 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/">Minkowski-Siegel mass constants</a>
%H A054911 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/">Minkowski-Siegel mass constants</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/abel/abel.html
%H A000688 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/abel/abel.html">Abelian Group Enumeration Constants</a> [broken link?]

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/apery/apery.html
%H A021002 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/apery/apery.html">Apery's Constant</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/brun/brun.html
%H A065421 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/brun/brun.html">Brun's Constant</a>

# ??? page 180-183
# http://web.archive.org/web/20010604180137/http://www.mathsoft.com/asolve/constant/cameron/cameron.html
%H A007865 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cameron/sf/sf.html">Several Problems Concerning Sum-Free Sets</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/catalan/catalan.html
%H A054543 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/catalan/catalan.html">Catalan's Constant</a> [Broken link]

# ??? c.f. Monomer dimer
%H A099390 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/catalan/dimer.html">The Dimer Problem</a>
%H A004003 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/catalan/dimer.html">The Dimer Problem</a> [Dead link]

# ??? 5.10 Self-Avoiding Walk Constants, p. 331 ff.
%H A001411 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cnntv/cnntv.html">Self-Avoiding-Walk Connective Constants</a>
%H A001412 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cnntv/cnntv.html">Self-Avoiding-Walk Connective Constants</a>
%H A007764 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cnntv/cnntv.html">Self-Avoiding-Walk Connective Constants</a>

# ??? 5.10.2 Rook Paths on a Chessboard, p. 334
%H A006192 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cnntv/gammel/gammel.html">Self-Avoiding Walks of a Rook on a Chessboard</a>
%H A064297 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cnntv/gammel/gammel.html">Self-Avoiding Walks of a Rook on a Chessboard</a>
%H A064298 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cnntv/gammel/gammel.html">Self-Avoiding Walks of a Rook on a Chessboard</a>

# http://web.archive.org/web/20010208143502/http://www.mathsoft.com/asolve/constant/cntfrc/mnkwsk.html
%H A048817 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cntfrc/mnkwsk.html">Minkowski's Question Mark Function</a>
%H A048818 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cntfrc/mnkwsk.html">Minkowski's Question Mark Function</a>
%H A048819 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cntfrc/mnkwsk.html">Minkowski's Question Mark Function</a>
%H A048820 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cntfrc/mnkwsk.html">Minkowski's Question Mark Function</a>
%H A048821 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cntfrc/mnkwsk.html">Minkowski's Question Mark Function</a>
%H A048822 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/cntfrc/mnkwsk.html">Minkowski's Question Mark Function</a>

# http://web.archive.org/web/20010413214937/http://www.mathsoft.com:80/asolve/constant/dig/dig.html
%H A048652 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a>
%H A065443 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a>
%H A065445 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a>
%H A065446 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a>
%H A066766 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a>
%H A066767 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a>
%H A066772 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a>
%H A048651 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a> [Broken link]
%H A065442 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a> [Broken link]
%H A065444 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/dig/dig.html">Digital Search Tree Constants</a> [Broken link]

# ??? Steven Finch, <a href="https://arxiv.org/abs/math/9912036">A Convex Maximization Problem: Continuous Case</a> and 
# ??? <a href="https://arxiv.org/abs/math/9912035">A Convex Maximization Problem: Discrete Case</a>
%H A014011 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/erdos/convex/convex.html">A Convex Maximization Problem</a>
%H A051741 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/erdos/convex/convex.html">A Convex Maximization Problem</a> [Broken link]
%H A051742 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/erdos/convex/convex.html">A Convex Maximization Problem</a> [Broken link]

# http://web.archive.org/web/20010620000306/http://www.mathsoft.com/asolve/constant/erdos/erdos.html
%H A014011 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/erdos/erdos.html">Erdos's Reciprocal Sum Constants</a>
%H A051741 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/erdos/erdos.html">Erdos's Reciprocal Sum Constants</a> [Broken link]
%H A051742 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/erdos/erdos.html">Erdos's Reciprocal Sum Constants</a> [Broken link]
%H A046185 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/erdos/erdos.html">Erdos's Reciprocal Sum Constants</a> [broken link]

# http://web.archive.org/web/20010622230958/http://www.mathsoft.com/asolve/constant/glshkn/glshkn.html
%H A000178 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/glshkn/glshkn.html">Glaisher-Kinkelin Constant</a> (gives asymptotic expressions for A002109, A000178) [At present this link does not work]
%H A002109 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/glshkn/glshkn.html">Glaisher-Kinkelin Constant</a> (gives asymptotic expressions for A002109, A000178) [At present this link does not work]

# http://fs.unm.edu/SF/TheAverageValue.pdf
%H A057108 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/golomb/smarand/smarand1.html">The Average Value of the Smarandache Function</a>
%H A057109 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/golomb/smarand/smarand1.html">The Average Value of the Smarandache Function</a>

# http://web.archive.org/web/20010604201556/http://www.mathsoft.com/asolve/constant/hdmrd/hdmrd.html
%H A075986 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hdmrd/hdmrd.html">Meissel-Mertens Constants</a>

# http://web.archive.org/web/20010208112444/http://www.mathsoft.com/asolve/constant/hdmrd/jacobi.html
%H A053760 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hdmrd/jacobi.html">Quadratic Residues</a>
%H A053761 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hdmrd/jacobi.html">Quadratic Residues</a>

# http://web.archive.org/web/20010614100031/http://www.mathsoft.com/asolve/constant/hrdyltl/hrdyltl.html
%H A059865 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hrdyltl/hrdyltl.html">Hardy-Littlewood Constants </a>
%H A059861 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hrdyltl/hrdyltl.html">Hardy-Littlewood Constants</a>
%H A059862 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hrdyltl/hrdyltl.html">Hardy-Littlewood Constants</a>
%H A059863 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hrdyltl/hrdyltl.html">Hardy-Littlewood Constants</a>
%H A059864 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hrdyltl/hrdyltl.html">Hardy-Littlewood Constants</a>
%H A061642 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hrdyltl/hrdyltl.html">Hardy-Littlewood Constants</a> [Broken link]
%H A062270 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hrdyltl/hrdyltl.html">Hardy-Littlewood constants</a>
%H A062271 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/hrdyltl/hrdyltl.html">Hardy-Littlewood constants</a>

# http://web.archive.org/web/20010608041254/http://www.mathsoft.com/asolve/constant/ice/ice.html
%H A054759 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/ice/ice.html">Lieb's Square Ice Constant</a>

# http://web.archive.org/web/20011108021950/http://www.mathsoft.com/asolve/constant/khntchn/khntchn.html
%H A054544 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/khntchn/khntchn.html">Khintchine's Constant</a>
%H A086702 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/khntchn/khntchn.html">Khintchine's constant</a>.
%H A086703 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/khntchn/khntchn.html">Khintchine's constant</a>.

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/kuzmin/kuzmin.html
%H A038517 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/kuzmin/kuzmin.html">The Gauss-Kuzmin-Wirsing Constant</a>

# ??? 6.6, p. 433-434 "Lehmer's Constant"
# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/lehmer/lehmer.html
%H A002065 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lehmer/lehmer.html">Lehmer's Constant</a>
%H A030125 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lehmer/lehmer.html">Lehmer's Constant</a>
# man %H A081796 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/iteration/article/">Lehmer constant</a>

# ??? 2.12 Linnik’s Constant p. 127-130
%H A034693 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/linnik/linnik.html">More about Linnik's Constant</a>
%H A034694 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/linnik/linnik.html">More about Linnik's Constant</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/lngy/lngy.html
%H A005121 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lngy/lngy.html">Lengyel's Constant</a>

# http://web.archive.org/web/20010413222037/http://www.mathsoft.com/asolve/constant/lpc/lpc.html
%H A033260 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lpc/lpc.html">Laplace Limit Constant</a>
%H A033261 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lpc/lpc.html">Laplace Limit Constant</a>
%H A033262 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lpc/lpc.html">Laplace Limit Constant</a>
%H A033263 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lpc/lpc.html">Laplace Limit Constant</a>
%H A033259 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lpc/lpc.html">Laplace Limit Constant</a> [Broken link]

# http://web.archive.org/web/20010605004309/http://www.mathsoft.com/asolve/constant/lr/lr.html
%H A004144 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lr/lr.html">Landau-Ramanujan Constant</a>
%H A009003 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lr/lr.html">Landau-Ramanujan Constant</a>
%H A022544 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lr/lr.html">Landau-Ramanujan Constant</a>
%H A064533 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/lr/lr.html">Landau-Ramanujan Constant</a>

# http://web.archive.org/web/20010608043455/http://www.mathsoft.com/asolve/constant/md/md.html
%H A099390 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/md/md.html">Two Dimensional Monomer Dimer Constant</a>
%H A004003 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/md/md.html">Two Dimensional Monomer Dimer Constant</a> [Dead link]
%H A028420 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/md/md.html">Two Dimensional Monomer-Dimer Constant</a>
%H A210662 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/md/md.html">Two Dimensional Monomer-Dimer Constant</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/mills/mills.html
%H A051254 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/mills/mills.html">Mills' Constant</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/onenin/onenin.html
%H A002129 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/onenin/onenin.html">The "One-Ninth" Constant</a>
%H A072558 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/onenin/onenin.html">The One-Ninth Constant</a>

# http://web.archive.org/web/20010624104257/http://www.mathsoft.com/asolve/constant/plff/plff.html
%H A004715 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>
%H A004716 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>
%H A004717 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>
%H A066770 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>
%H A066771 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>
%H A067358 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>
%H A067359 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>
%H A067360 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>
%H A067361 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plff/plff.html">Plouffe's Constant</a>

# http://web.archive.org/web/20010603082348/http://www.mathsoft.com/asolve/plouffe/plouffe.html
%H A072136 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/plouffe/plouffe.html">The Miraculous Bailey-Borwein-Plouffe Pi Algorithm</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/polya/polya.html
%H A063888 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/polya/polya.html">Polya's Random Walk Constants</a>

# ??? 2.30.1 Powers of 3/2 Modulo One p. 194-197
%H A071291 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/pvs/pwrs32/pwrs32.html">Powers of 3/2</a>
%H A071315 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/pvs/pwrs32/pwrs32.html">Powers of 3/2</a>
%H A071316 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/pvs/pwrs32/pwrs32.html">Powers of 3/2</a>
%H A071337 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/pvs/pwrs32/pwrs32.html">Powers of 3/2</a>
%H A071353 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/pvs/pwrs32/pwrs32.html">Powers of 3/2</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/rndprc/anml.html
%H A001168 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/rndprc/anml.html">Klarner's Lattice Animal Constant</a>

# http://web.archive.org/web/20010605012506/http://www.mathsoft.com/asolve/constant/square/square.html
%H A006506 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/square/square.html">Hard Square Entropy Constant</a>
%H A050974 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/square/square.html">Hard Square Entropy Constant</a>
%H A066863 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/square/square.html">Hard Square Entropy Constant</a>
%H A066864 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/square/square.html">Hard Square Entropy Constant</a>
%H A066865 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/square/square.html">Hard Square Entropy Constant</a>
%H A066866 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/square/square.html">Hard Square Entropy Constant</a>
%H A067967 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/square/square.html">Hard Square Entropy Constant</a>
%H A067968 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/square/square.html">Hard Square Entropy Constant</a>

# http://web.archive.org/web/20010207201533/http://www.mathsoft.com:80/asolve/constant/srp/srp.html
%H A062083 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/srp/srp.html">Sierpinski's Constant.</a>
%H A062089 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/srp/srp.html">Sierpinski's Constant.</a>

# ??? 2.16.2 Ulam 1-Additive Sequences, p. 147-148
# https://projecteuclid.org/download/pdf_1/euclid.em/1062621142
%H A001857 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/sadd/sadd.html">Ulam s-Additive Sequences</a>
%H A002858 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/sadd/sadd.html">Ulam s-Additive Sequences</a>
%H A002859 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/sadd/sadd.html">Ulam s-Additive Sequences</a>
%H A003044 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/sadd/sadd.html">Ulam s-Additive Sequences</a>

# http://web.archive.org/web/20010207195349/http://www.mathsoft.com/asolve/constant/stlrsky/stlrsky.html
%H A001316 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/stlrsky.html">Stolarsky-Harborth Constant</a>
%H A002858 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/stlrsky.html">Stolarsky-Harborth Constant</a>
%H A003670 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/stlrsky.html">Stolarsky-Harborth Constant</a>
%H A006844 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/stlrsky.html">Stolarsky-Harborth Constant</a>
%H A072832 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/stlrsky/stlrsky.html">Stolarsky-Harborth Constant</a>

# http://web.archive.org/web/20010603070928/http://www.mathsoft.com/asolve/constant/totient/totient.html
%H A061091 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/totient/totient.html">Euler Totient Function Asymptotic Constants</a>
%H A002088 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/constant/totient/totient.html">Euler Totient Function Asymptotic Constants</a> [broken link]

# ??? page 164 2.20.2 B<sub>2</sub>-Sequences
%H A046185 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/rlewis.html">Mian-Chowla and B2 sequences</a>

# https://web.archive.org/web/20150911081920/http://www.people.fas.harvard.edu/~sfinch/csolve/seqmod3.pdf
%H A046932 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/seqmod3.pdf">Periodicity in Sequences Mod 3</a>
%H A112683 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/seqmod3.pdf">Periodicity in Sequences Mod 3</a>
%H A112684 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/seqmod3.pdf">Periodicity in Sequences Mod 3</a>

# ??? https://books.google.de/books?id=Pl5I2ZSI6uAC&pg=PA183&lpg=PA187
# ??? https://web.archive.org/web/20150911081529/http://www.people.fas.harvard.edu/~sfinch/csolve/triple/
# ??? whole book on https://id.b-ok.org/book/894221/165946, p. 183-186
# https://oeis.org/w/images/3/35/Triple-free_Set_Constants.pdf
%H A004059 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A050291 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A050292 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A050294 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A050296 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A057561 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A086316 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A094708 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A157244 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A157245 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A157271 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A157282 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a>
%H A050293 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a> [broken link]
%H A050295 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a> [broken link]
%H A068060 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a> [broken link]
%H A088808 S. R. Finch, <a href="http://www.people.fas.harvard.edu/~sfinch/csolve/triple/">Triple-Free Sets of Integers</a> [broken link]
