-- Table for OEIS broken link maintenance
-- @(#) $Id$
-- 2018-12-13 17:52:32 - generated by brol_prepare.pl -c url1, do not edit here!
DROP    TABLE  IF EXISTS url1;
CREATE  TABLE            url1
    ( protocol   VARCHAR(8)
    , host       VARCHAR(64)
    , port       VARCHAR(8)
    , path       VARCHAR(250)
    , filename   VARCHAR(250)
    , noccur     INT
    , status     VARCHAR(32)
    , access     TIMESTAMP
    , PRIMARY KEY(protocol, host, port, path, filename)
    );
COMMIT;
