#!perl

# Read A-numbers from infile1 and mark the corresponding A-numbers in infile2
# @(#) $Id$
# 2024-06-05, Georg Fischer: copied from dex_join.pl
#
#:# Usage:
#:#   perl classify.pl [-d debug] [-m marker] -f infile1 ifile2 > outfile
#:#       -m uppercase letter for the marker (from column 2 if not specified)
#--------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min);
my $pwd = `pwd`;
$pwd =~ m{(/OEIS\-mat\S*)};
print "# Generated by ..$1/$0 at $timestamp\n";
if (0 && scalar(@ARGV) == 0) {
    print `grep -E "^#:#" $0 | cut -b3-`;
    exit;
}
my $debug = 0;
my $marker = "";
my $infile1 = "x.tmp";
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } elsif ($opt  =~ m{f}) {
        $infile1   = shift(@ARGV);
    } elsif ($opt  =~ m{m}) {
        $marker    = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my %hash = ();
open (IN1, "<", $infile1) || die "cannot read $infile1\n";
while (<IN1>) {
    s/\s+\Z//; # chompr
    next if $_ !~ m{\AA\d+};
    my $line = $_;
    my ($aseqno, $m) = split(/\t/, $line);
    if (length($marker) == 1) {
        $hash{$aseqno} = $marker;
    } else {
        $hash{$aseqno} = $m;
    }
} # while <IN1>
close(IN1);

while (<>) {
    my $line = $_;
    #                 1 2     21
    while ($line =~ s{(A(\d{6}))}{defined($hash{$1}) ? "$hash{$1}$2" : "_$2_"}eg) {
    } # while
    $line =~ s{_(\d+)_}{A$1}g;
    print $line;
} # while
__DATA__
%F A205885 Equals A073006/6.
%F A206161 Equals A093954 * A144981 / A068465 .
%F A206769 Equals A093954 * A182168 / A068465.
%F A210462 Equals 1/2 + 1/(2*A075778*(A075778+1)).
%F A211705 Equals 2 * A065442. - _Amiram Eldar_, Aug 01 2020
%F A213053 Equals -1 / sqrt(1 + A115365^2) = cos(A115365). - _Álvar Ibeas_, Jul 28 2017
%F A214550 Equals 4*Pi^2/27 - A294967. (End)
%F A216542 Equals A013706/2. - _Hugo Pfoertner_, Apr 23 2024
