#!perl

# Read X-numbers and formulas from infile1 and and replace X-numbers in infile2 by the corresponding formula
# @(#) $Id$
# 2024-06-05, Georg Fischer
#
#:# Usage:
#:#   perl replace_known.pl [-d debug] -f infile1 ifile2 > outfile
#--------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min);
my $pwd = `pwd`;
$pwd =~ m{(/OEIS\-mat\S*)};
print "# Generated by ..$1/$0 at $timestamp\n";
if (0 && scalar(@ARGV) == 0) {
    print `grep -E "^#:#" $0 | cut -b3-`;
    exit;
}
my $debug = 0;
my $marker = "X";
my $infile1 = "x.tmp";
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } elsif ($opt  =~ m{f}) {
        $infile1   = shift(@ARGV);
    } elsif ($opt  =~ m{m}) {
        $marker    = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my %hash = ();
open (IN1, "<", $infile1) || die "cannot read $infile1\n";
while (<IN1>) {
    s/\s+\Z//; # chompr
    my $line = $_;
    my ($aseqno, $callcode, $offset, $expr, @rest) = split(/\t/, $line);
    if ($debug >= 1) {
        print "# $marker $aseqno $expr\n";
    }
    if ($callcode eq $marker) {
        $hash{$marker . substr($aseqno, 1)} = $expr;
    }
} # while <IN1>
close(IN1);

while (<>) {
    my $line = $_;
    my ($aseqno, $callcode, $offset, $expr, @rest) = split(/\t/, $line);
    #                 1       2     21
    while ($expr =~ s{($marker(\d{6}))}{$hash{$1}}g) {
    } # while
    print join("\t", $aseqno, $callcode, $offset, $expr, @rest) . "\n";
} # while
__DATA__
A098459	decexp	0	CR.HALF.*(X006752).+(X102886)	u=X006752,v=X102886	(1/2)*X006752+X102886
A372609	decexp	0	CV(new Q(10,3)).*(X193535)	u=X193535	(10/3)*X193535
A271780	decexp	0	CR.PI.^(2)./(8).*(X005597)	u=X005597	(8/CR.PI^2)*X005597
