--  Table for OEIS - sequence terms in DATA sections (%S, %T, %U records in CAT25)
--  @(#) $Id$
--  2026-03-23T09:13:28z: Georg Fischer - generated by extract_asdata.pl - do NOT edit here!
--
DROP    TABLE  IF EXISTS asdata;
CREATE  TABLE            asdata
    ( aseqno    VARCHAR(10)   -- A322469
    , termno    INT           -- number of terms in column 'data'
    , data      VARCHAR(1280)
    , PRIMARY KEY(aseqno)
    );
CREATE  INDEX  asdatad ON asdata
    (data       ASC
    );
COMMIT;
