--  Table for OEIS - sequence terms in DATA sections (%S, %T, %U records in CAT25)
--  @(#) $Id$
--  2026-04-23T07:20:25z: Georg Fischer - generated by extract_bfdata.pl - do NOT edit here!
--
DROP    TABLE  IF EXISTS bfdata;
CREATE  TABLE            bfdata
    ( aseqno    VARCHAR(10)   -- A322469
    , termno    INT           -- number of terms in column 'data'
    , data      VARCHAR(1280)
    , PRIMARY KEY(aseqno)
    );
CREATE  INDEX  bfdatad ON bfdata
    (data       ASC
    );
COMMIT;
