#!perl

# Create a db table for draft listings
# @(#) $Id$
# 2019-01-25: rewritten for -t json
# 2019-01-17: Georg Fischer, copied from ../broken_link/brol_process.pl
#
#:# Usage:
#:#   perl draft.pl -c > draft.create.sql
#------------------------------------
use strict;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = gmtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d.%02d_%02d"
        , $year + 1900, $mon + 1, $mday, $hour, $min);

my $debug      = 0;
my $action     = "g";
my $sleep      = 16; # wait time in seconds
if (scalar(@ARGV) == 0) {
    print `grep -E "^#:#" $0 | cut -b3-`;
    exit;
}
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A\-})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{c}) {
        $action    =   "c";
    } elsif ($opt  =~ m{w}) {
        $sleep      =  shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my $outdir = $timestamp;
if (scalar(@ARGV) > 0) {
    $outdir = shift(@ARGV);
}
print `mkdir $outdir`;
if (0) {
#-------------------------------------------------------------
} elsif ($action =~ m{c}) {
    print <<"GFis";
--  Table for OEIS - information about drafts
--  \@(#) \$Id$
--  $timestamp: Georg Fischer - generated by draft.pl -c, do not edit here!
--
DROP    TABLE  IF EXISTS draft;
CREATE  TABLE            draft
    ( aseqno    VARCHAR(10)   -- A322469
    , linadd    INT           -- number of additinal lines
    , linsub    INT           -- number of removed lines
    , status    VARCHAR(16)   -- edited, proposed, reviewed
    , author    VARCHAR(80)   -- of draft
    , reviewer  VARCHAR(80)   -- 
    , access    TIMESTAMP     -- modification time in UTC
    , PRIMARY KEY(aseqno)
    );
COMMIT;
GFis
#-------------------------------------------------------------
} else {
    die "invalid action \"$action\"\n";
}
#=====================================
sub iso_time {
    my ($unix_time) = @_;
} # iso_time
#=====================================
__DATA__

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
  
  <head>
  <style>
  tt { font-family: monospace; font-size: 100%; }
  p.editing { font-family: monospace; margin: 10px; text-indent: -10px; word-wrap:break-word;}
  p { word-wrap: break-word; }
  </style>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="keywords" content="OEIS,integer sequences,Sloane" />
  
  
  <title>The On-Line Encyclopedia of Integer Sequences&reg; (OEIS&reg;)</title>
  <link rel="search" type="application/opensearchdescription+xml" title="OEIS" href="/oeis.xml">
  <script>
  function sf() {
      if(document.location.pathname == "/" && document.f) document.f.q.focus();
  }
  </script>
  </head>
  <body bgcolor=#ffffff onload="sf()">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr><td width="100%" align="right">
      <font size=-1>
      
        <a href="/login?redirect=%2fdraft%3fstart%3d000">login</a>
      
      </font>
    <tr height=5><td>
    </table>

    <center>
    <span style="font-family: sans-serif; font-size: 83%; font-style: italic">This site is supported by donations to <a href="http://oeisf.org">The OEIS Foundation</a>.</span>

    <br>
<p style="margin-top:-24px">&nbsp;</p>
<a href="/"><img border="0" width="600" height="118" src="/Luschny4.png" alt="Logo" /></a>
    <br>
<p>


<font color="green" ><strong>
</strong></font>


<br>


    <!-- no special fonts -->
    </center>
  
    <center>
    <table border="0" cellspacing="0" cellpadding="0">
      <tr><td>
        
    
    <center>
        <form name=f action="/search" method="GET">
            <table cellspacing=0 cellpadding=0 border=0>
            <tr><td>
            <input maxLength=1024 size=55 name=q value="" title="Search Query">
            <input type=hidden name=sort value="">
            <input type=hidden name=language value="">
            <input type=submit value="Search" name=go>
            <td width=10><td>
            <font size=-2><a href="/hints.html">Hints</a></font>
            <tr><td colspan=2>
            <font size=-1>
                (Greetings from <a href="/welcome">The On-Line Encyclopedia of Integer Sequences</a>!)
            </font>
            </table>
        </form>
    </center>

    <center>
    <h2 style="margin-top: 0; margin-bottom:0;">
        
            Proposed drafts
        
    </h2>
    (In many browsers, middle-clicking on any of the links below will open it in a new tab.
        <br>
        See also <a href="/draft/editing">drafts not yet proposed for review</a>.)
    </center>
    <br>
    
    <table cellspacing=2 cellpadding=0 border=0>
        <tr><td colspan=9 align=right>
            
    
        
        Showing entries 1-100
        
            | <a href="/draft?start=100">older changes</a>
        
    

        <tr>
            <th align=left>Sequence<th width=10>
            <th align=left>Status<th width=10>
            <th align=left>Time<th width=10>
            <th align=left width=200>Draft by<th width=10>
            <th align=left width=200>Reviewed or edited by<th width=10>
            <th align=left>
        <tr height=1 bgcolor="#cccccc"><td colspan=9>
        
        
            
            <tr>
                <td><a href="/draft/A321788">A321788</a>
                <td><td>reviewed
                    +11
                    &#x2212;2
                <td><td>Nov 18 21:04
                <td><td><a href="/draft?user=G.%20L.%20Honaker%2c%20Jr.">G. L. Honaker, Jr.
                    
                     (2/7) 
                <td><td>
                    
                        Georg Fischer
                    
            <tr height=1 bgcolor="#cccccc"><td colspan=9>
        
            
            <tr>
                <td><a href="/draft/A323250">A323250</a>
                <td><td>proposed
                    +13
                    &#x2212;2
                <td><td>Jan 08 08:04
                <td><td><a href="/draft?user=Paolo%20P.%20Lava">Paolo P. Lava
                    
                     (3) 
                <td><td>
                    
                        Jinyuan Wang
                    
            <tr height=1 bgcolor="#cccccc"><td colspan=9>
        
            
            <tr>
                <td><a href="/draft/A323711">A323711</a>
                <td><td>proposed
                    +15
                    &#x2212;3
                <td><td>Feb 01 11:24
                <td><td><a href="/draft?user=Chai%20Wah%20Wu">Chai Wah Wu
 