--  Table for OEIS - information about drafts
--  @(#) $Id0-  2019-02-20.13_53: Georg Fischer - generated by draft.pl -c, do not edit here!
--
DROP    TABLE  IF EXISTS draft;
CREATE  TABLE            draft
    ( aseqno    VARCHAR(10)   -- A322469
    , linadd    INT           -- number of additinal lines
    , linsub    INT           -- number of removed lines
    , status    VARCHAR(16)   -- edited, proposed, reviewed
    , author    VARCHAR(80)   -- of draft
    , reviewer  VARCHAR(80)   -- 
    , access    TIMESTAMP     -- modification time in UTC
    , PRIMARY KEY(aseqno)
    );
COMMIT;
