#!perl

# Get the OEIS history for keywords "new", "changed" or "recycled"
# @(#) $Id$
# 2019-01-25: rewritten for -t json
# 2019-01-17: Georg Fischer, copied from ../broken_link/brol_process.pl
#
# Usage:
#   perl history.pl [-k (new|changed|recycled)] [-n maxnum] [-w sleep] [-t (text|json)] [outputdir]
#       -k    for keyword kw (default "changed")
#       -n    fetch a maximum of n sequences 
#       -w    wait time in seconds (default 16)
#       -t    format, "text" or "json"
#       outputdir (default yyyy-mm-dd)
#------------------------------------
use strict;
use warnings;
use LWP;
use LWP::UserAgent;
use LWP::RobotUA;
use HTTP::Request::Common;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = gmtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d.%02d_%02d"
        , $year + 1900, $mon + 1, $mday, $hour, $min);

my $debug      = 0;
my $action     = "g";
my $keyword    = "changed";
my $maxnum     = 65536; # maximum number of sequences (default unlimited)
my $increment  = 10; # for &start, fixed by OEIS server
my $sleep      = 16; # wait time in seconds
my $type       = "json";
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A\-})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{c}) {
        $action    =   "c";
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } elsif ($opt  =~ m{k}) {
        $action    = "g";
        $keyword   = shift(@ARGV);
    } elsif ($opt  =~ m{n}) {
        $maxnum    = shift(@ARGV);
    } elsif ($opt  =~ m{r}) {
        $action    =   "r";
    } elsif ($opt  =~ m{w}) {
        $sleep      =  shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my $outdir = $timestamp;
if (scalar(@ARGV) > 0) {
    $outdir = shift(@ARGV);
}
print `mkdir $outdir`;
if (0) {
#-------------------------------------------------------------
} elsif ($action =~ m{g}) { # get blocks of 10 sequences
    my $ua;
    if (1) {
        $ua = LWP::UserAgent->new;
        $ua->agent("Mozilla/8.0"); # pretend we are a capable browser
        # $ua->agent("Chrome/70.0.3538.110");
    } else { # robot
        $ua = LWP::RobotUA->new('EiC-gfis/1.0', 'georg.fischer@t-online.de');
        $ua->delay($sleep/60);
    }
    $ua->timeout(6); # give up if server does not respond in time
    my $url = "https://oeis.org/search?q="
        . join("\&", ( "keyword:$keyword"
                     , "sort=" . ($keyword eq "new" ? "created" : "modified")
                     , "fmt=$type"
                     , "start="));
    my $start  = 0;
    my $total  = 0;
    while ($start < $maxnum) {
        my $status = "000";
        print STDERR "read $url$start\n";
        my $response = $ua->request(GET "$url$start");
        # print STDERR "status " . $response->code() . "\n";
        my $page  = $response->decoded_content(charset => 'UTF-8');
        $status   = $response->code();
        if ($status ne "200") {
            die "bad status $status\n";
        }
        my $outname = sprintf("$outdir/${keyword}_%04d\.$type", $start);
        open (OUT, ">", $outname) || die "cannot write \"$outname\"\n";
        print OUT "$page\n";
        close(OUT);
        #   "count": 451,
        $page =~ m{\n\t+\"count\"\: (\d+)\,}m;
        my $count = $1;
        #           "time": "2019-01-25T04:04:11-05:00",
        my @modtimes = ($page =~ m{\n\t+\"time\"\: \"([0-9\-\:T\+]+)\"\,}mg);
        $total += scalar(@modtimes);
        print STDERR "-> $outname\t$count\n";
        foreach my $modtime(@modtimes) {
            print STDERR "$modtime\n";
        } # foreach
        $start += $increment;
        if ($count == 0 or $count < $start) {
            $start = $maxnum; # break loop
        } else { # continue
            print STDERR "sleep $sleep s\n"; 
            sleep $sleep;
        }
    } # while $start < $count
    print STDERR "history.pl read $total sequences for keyword \"$keyword\"\n";
#-------------------------------------------------------------
} elsif ($action =~ m{c}) {
    print <<"GFis";
--  Table for OEIS - information about drafts
--  \@(#) \$Id$
--  $timestamp: Georg Fischer - generated by draft.pl -c, do not edit here!
--
DROP    TABLE  IF EXISTS draft;
CREATE  TABLE            draft
    ( aseqno    VARCHAR(10)   -- A322469
    , linadd    INT           -- number of additinal lines
    , linsub    INT           -- number of removed lines
    , status    VARCHAR(16)   -- edited, proposed, reviewed
    , author    VARCHAR(80)   -- of draft
    , reviewer  VARCHAR(80)   -- 
    , access    TIMESTAMP     -- modification time in UTC
    , PRIMARY KEY(aseqno)
    );
COMMIT;
GFis
#-------------------------------------------------------------
} else {
    die "invalid action \"$action\"\n";
}
#=====================================
sub iso_time {
    my ($unix_time) = @_;
} # iso_time
#=====================================
__DATA__

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
  
  <head>
  <style>
  tt { font-family: monospace; font-size: 100%; }
  p.editing { font-family: monospace; margin: 10px; text-indent: -10px; word-wrap:break-word;}
  p { word-wrap: break-word; }
  </style>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="keywords" content="OEIS,integer sequences,Sloane" />
  
  
  <title>The On-Line Encyclopedia of Integer Sequences&reg; (OEIS&reg;)</title>
  <link rel="search" type="application/opensearchdescription+xml" title="OEIS" href="/oeis.xml">
  <script>
  function sf() {
      if(document.location.pathname == "/" && document.f) document.f.q.focus();
  }
  </script>
  </head>
  <body bgcolor=#ffffff onload="sf()">
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr><td width="100%" align="right">
      <font size=-1>
      
        <a href="/login?redirect=%2fdraft%3fstart%3d000">login</a>
      
      </font>
    <tr height=5><td>
    </table>

    <center>
    <span style="font-family: sans-serif; font-size: 83%; font-style: italic">This site is supported by donations to <a href="http://oeisf.org">The OEIS Foundation</a>.</span>

    <br>
<p style="margin-top:-24px">&nbsp;</p>
<a href="/"><img border="0" width="600" height="118" src="/Luschny4.png" alt="Logo" /></a>
    <br>
<p>


<font color="green" ><strong>
</strong></font>


<br>


    <!-- no special fonts -->
    </center>
  
    <center>
    <table border="0" cellspacing="0" cellpadding="0">
      <tr><td>
        
    
    <center>
        <form name=f action="/search" method="GET">
            <table cellspacing=0 cellpadding=0 border=0>
            <tr><td>
            <input maxLength=1024 size=55 name=q value="" title="Search Query">
            <input type=hidden name=sort value="">
            <input type=hidden name=language value="">
            <input type=submit value="Search" name=go>
            <td width=10><td>
            <font size=-2><a href="/hints.html">Hints</a></font>
            <tr><td colspan=2>
            <font size=-1>
                (Greetings from <a href="/welcome">The On-Line Encyclopedia of Integer Sequences</a>!)
            </font>
            </table>
        </form>
    </center>

    <center>
    <h2 style="margin-top: 0; margin-bottom:0;">
        
            Proposed drafts
        
    </h2>
    (In many browsers, middle-clicking on any of the links below will open it in a new tab.
        <br>
        See also <a href="/draft/editing">drafts not yet proposed for review</a>.)
    </center>
    <br>
    
    <table cellspacing=2 cellpadding=0 border=0>
        <tr><td colspan=9 align=right>
            
    
        
        Showing entries 1-100
        
            | <a href="/draft?start=100">older changes</a>
        
    

        <tr>
            <th align=left>Sequence<th width=10>
            <th align=left>Status<th width=10>
            <th align=left>Time<th width=10>
            <th align=left width=200>Draft by<th width=10>
            <th align=left width=200>Reviewed or edited by<th width=10>
            <th align=left>
        <tr height=1 bgcolor="#cccccc"><td colspan=9>
        
        
            
            <tr>
                <td><a href="/draft/A321788">A321788</a>
                <td><td>reviewed
                    +11
                    &#x2212;2
                <td><td>Nov 18 21:04
                <td><td><a href="/draft?user=G.%20L.%20Honaker%2c%20Jr.">G. L. Honaker, Jr.
                    
                     (2/7) 
                <td><td>
                    
                        Georg Fischer
                    
            <tr height=1 bgcolor="#cccccc"><td colspan=9>
        
            
            <tr>
                <td><a href="/draft/A323250">A323250</a>
                <td><td>proposed
                    +13
                    &#x2212;2
                <td><td>Jan 08 08:04
                <td><td><a href="/draft?user=Paolo%20P.%20Lava">Paolo P. Lava
                    
                     (3) 
                <td><td>
                    
                        Jinyuan Wang
                    
            <tr height=1 bgcolor="#cccccc"><td colspan=9>
        
            
            <tr>
                <td><a href="/draft/A323711">A323711</a>
                <td><td>proposed
                    +15
                    &#x2212;3
                <td><td>Feb 01 11:24
                <td><td><a href="/draft?user=Chai%20Wah%20Wu">Chai Wah Wu
 