#!perl

# Extract information about b-files from oeisdata/files subdirectories
# @(#) $Id$
# 2026-02-17, Georg Fischer
#
#:# usage:
#:#   perl extract_asdata.pl [-d mode] jcat25.txt > asdata.txt
#:#   perl extract_asdata.pl [-d mode] -c         > asdata.create.sql
#:#       -d mode    debug mode: none(0), some(1), more(2)
#---------------------------------
use strict;
use integer;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday) = gmtime (time);
my $utc_stamp = sprintf ("%04d-%02d-%02dT%02d:%02d:%02d\z"
        , $year + 1900, $mon + 1, $mday, $hour, $min, $sec);

# get options
my $debug      =  0; # 0 (none), 1 (some), 2 (more)
my $tabname = "asdata";
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A\-})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt =~ m{\-d}) {
        $debug    = shift(@ARGV);
    } elsif ($opt =~ m{\-c}) {
        &print_create_sql();
        exit;
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while ARGV
#----
my ($type, $line, $nok, $aseqno, $termno, @terms);
$aseqno = "A000000";
print join("\t", $aseqno, 0, $utc_stamp) . "\n";
# while (<DATA>) {
while (<>) {
    s/\s+\Z//;
    ($type, $aseqno, $line) = split(/\s+/, $_, 3);
    $type = substr($type, 1);
    $nok  = "";
    $termno = -1;
    if (0) {
    } elsif ($type =~ m{I}) {
    	@terms = (); 
    } elsif ($type =~ m{[STU]}) { 
    	push(@terms, split(/\, */, $line));
    } elsif ($type =~ m{N}) { 
        $termno = scalar(@terms);
        print join("\t", $aseqno, $termno, join("\,", @terms)) . "\n";
    }
} # while <>
#----
sub print_create_sql {
    print <<"GFis";
--  Table for OEIS - sequence terms in DATA sections (%S, %T, %U records in CAT25)
--  @(#) \$Id\$
--  $utc_stamp: Georg Fischer - generated by extract_asdata.pl - do NOT edit here!
--
DROP    TABLE  IF EXISTS asdata;
CREATE  TABLE            asdata
    ( aseqno    VARCHAR(10)   -- A322469
    , termno    INT           -- number of terms in column 'data'
    , data      VARCHAR(1280)
    , PRIMARY KEY(aseqno)
    );
CREATE  INDEX  asdatad ON asdata
    (data       ASC
    );
COMMIT;
GFis
#-- INSERT INTO asdata VALUES('A000000', 0, CURRENT_TIMESTAMP);
} # print_create_sql
#----
__DATA__
%I A063787 #99 Jan 12 2024 01:13:12
%S A063787 1,2,2,3,2,3,3,4,2,3,3,4,3,4,4,5,2,3,3,4,3,4,4,5,3,4,4,5,4,5,5,6,2,3,
%T A063787 3,4,3,4,4,5,3,4,4,5,4,5,5,6,3,4,4,5,4,5,5,6,4,5,5,6,5,6,6,7,2,3,3,4,
%U A063787 3,4,4,5,3,4,4,5,4,5,5,6,3,4,4,5,4,5,5,6,4,5,5,6,5,6,6,7,3,4,4,5,4,5,5,6,4
%N A063787 a(2^k) = k + 1 and a(2^k + i) = 1 + a(i) for k >= 0 and 0 < i < 2^k.
