#!perl

# Extract information about b-files from oeisdata/files subdirectories
# @(#) $Id$
# 2026-02-16, Georg Fischer
#
#:# usage:
#:#   perl extract_bfoeis.pl [-d mode] jcat25.txt > bfoeis.txt
#:#   perl extract_bfoeis.pl [-d mode] -c         > bfoeis.create.sql
#:#       -d mode    debug mode: none(0), some(1), more(2)
#---------------------------------
use strict;
use integer;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday) = gmtime (time);
my $utc_stamp = sprintf ("%04d-%02d-%02dT%02d:%02d:%02d\z"
        , $year + 1900, $mon + 1, $mday, $hour, $min, $sec);

# get options
my $debug      =  0; # 0 (none), 1 (some), 2 (more)
my $tabname = "bfoeis";
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A\-})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt =~ m{\-d}) {
        $debug    = shift(@ARGV);
    } elsif ($opt =~ m{\-c}) {
        &print_create_sql();
        exit;
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while ARGV
#----
my ($line, $nok, $aseqno, $sha256, $version, $fsize);
# while (<DATA>) {
while (<>) {
    s/\s+\Z//;
    $line = $_;
    $nok  = "";
    $fsize = -1;
    if (0) {
    } elsif ($line =~ m{\A\=\=}) {
        if ($line  =~ m{\/b(\d+)\.txt}) {
            $aseqno = "A$1";
        } else {
            $nok = "noseqno";
        }
    } elsif ($line =~ m{\Aversion}) {
        if ($line  =~ m{\/(v\d+)\Z}) {
            $version = $1;
        } else {
            $nok = "novers";
        }
    } elsif ($line =~ m{\Aoid}) {
        if ($line  =~ m{sha256\:([a-zA-Z0-9]+)\Z}) {
            $sha256 = $1;
        } else {
            $nok = "nosha";
        }
    } elsif ($line =~ m{\Asize (\d+)}) {
        $fsize = $1;
        print        join("\t", $aseqno, $fsize, $sha256, $version) . "\n";
    }
} # while <>
#----
sub print_create_sql {
    print <<"GFis";
--  Table for OEIS - information about b-files from oeisdata/files subdirectories
--  @(#) \$Id\$
--  $utc_stamp: Georg Fischer - generated by extract_bfoeis.pl - do NOT edit here!
--
DROP    TABLE  IF EXISTS $tabname;
CREATE  TABLE            $tabname
    ( aseqno        VARCHAR(10)   -- A322469
    , fsize         VARCHAR(16)   -- b-file size in bytes
    , sha256        VARCHAR(70)
    , version       VARCHAR(8)
    , PRIMARY KEY(aseqno)
    );
COMMIT;
GFis
} # print_create_sql
#----
__DATA__
==> ../../oeisdata/files/A004/b004041.txt <==
version https://git-lfs.github.com/spec/v1
oid sha256:71712bddeb4c271a510fefc96218f43c2b5e488abe607f39a806eb51584a1fb2
size 186996
==> ../../oeisdata/files/A004/b004042.txt <==
version https://git-lfs.github.com/spec/v1
oid sha256:9897b90f40e58d445438f20942a6932b483f64cfcb9c96ea1935bf9809f8a016
size 27217
==> ../../oeisdata/files/A004/b004046.txt <==
version https://git-lfs.github.com/spec/v1
oid sha256:e58e9c4521f4fbb4f1df60dc7ba7fafd7ee6804c6db0c45d986f2eb400b16ce1
size 73231
==> ../../oeisdata/files/A004/b004050.txt <==
version https://git-lfs.github.com/spec/v1
oid sha256:821ba9eb660658aa16662812b6e10405dddf7630c0e917b2a903521b7db251ed
size 314859
