#!perl

# Extract information about b-files from links in %H-records in a CAT25 file
# @(#) $Id$
# 2026-02-16, Georg Fischer
#
#:# usage:
#:#   perl extract_bflink.pl [-d mode] jcat25.txt > bflink.txt
#:#   perl extract_bflink.pl [-d mode] -c         > bflink.create.sql
#:#       -d mode    debug mode: none(0), some(1), more(2)
#---------------------------------
use strict;
use integer;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday) = gmtime (time);
my $utc_stamp = sprintf ("%04d-%02d-%02dT%02d:%02d:%02d\z"
        , $year + 1900, $mon + 1, $mday, $hour, $min, $sec);

# get options
my $debug      =  0; # 0 (none), 1 (some), 2 (more)
my $tabname = "bflink";
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A\-})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt =~ m{\-d}) {
        $debug    = shift(@ARGV);
    } elsif ($opt =~ m{\-c}) {
        &print_create_sql();
        exit;
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while ARGV
#----
my ($line, $type, $aseqno, $cc, $offset, $text, $bfimin, $bfimax, $rowmin, $rowmax);
# while (<DATA>) {
while (<>) {
    s/\s+\Z//;
    $type      = substr($_, 1, 1); # skip over [\#\%\?] in first column
    $line      = substr($_, 3);
    if (0) {
    } elsif ($type eq "H") { # link        
        #                 1   1                              2      2
        if ($line =~ m{\AA(\d+)[^\"]+\"\/[^\/]+\/b\1\.txt\"\>([^\<]+)}) {
            $aseqno = "A$1";
            $text   = $2;
            ($cc, $offset, $bfimin, $bfimax, $rowmin, $rowmax) = ("row", 0, "", "", "", "");
            if (0) {
            #                                           1      12                       23      3
            } elsif ($text =~ m{Table *of [i-n][^\=]*\= *(\-?\d+)(\.\.|\,\.\.\.\, ?|\,| to | through )(\-?\d+)}) { 
                ($bfimin, $bfimax) = ($1, $2);
                $cc = "bfi";
            #                                                  1   1   2   2
            } elsif ($text =~ m{Table of [i-nr]\,[^f]+for rows (\d+)\D+(\d+)}) { 
                ($rowmin, $rowmax) = ($1, $2);
            #                                       1      1
            } elsif ($text =~ m{Table of [i-nr]\,\D+(\-?\d+) (rows|antidiagonals)}) { 
                ($rowmin, $rowmax) = (1, $1);
            #                   1                                                     1 2                2 3      34                                 45      5
            } elsif ($text =~ m{(Antidiagonals|Layers|Rows?|Columns?|Antidiagonal rows) ([i-nr][^\=]*\= *)?(\-?\d+)(\.\.|\,\.\.\.\,|\,| to | through )(\-?\d+)}) { 
                ($rowmin, $rowmax) = ($3, $5);
            #                   1               1                          2      2    3      3
            } elsif ($text =~ m{(Falling |First )?Antidiagonals n[^\=]*\= *(\-?\d+)\.\.(\-?\d+)}i) { 
                ($rowmin, $rowmax) = ($2, $3);
            #                         1      1
            } elsif ($text =~ m{First *(\-?\d+) (antidiagonals|rows)}i) { 
                ($rowmin, $rowmax) = (1, $1);
            } else {
                $cc =  "err";
            }
            if ($cc ne "err") {
                print        join("\t", $aseqno, $cc, $offset, $bfimin, $bfimax, $rowmin, $rowmax, $text) . "\n";
            } else {
                print STDERR join("\t", $aseqno, $text) . "\n";
            }
        } elsif ($debug > 0) {
            print "? $line\n";
        }
    }
} # while <>
#----
sub print_create_sql {
    print <<"GFis";
--  Table for OEIS - information about b-files from links in sequences
--  @(#) \$Id\$
--  $utc_stamp: Georg Fischer - generated by extract_bflink.pl - do NOT edit here!
--
DROP    TABLE  IF EXISTS $tabname;
CREATE  TABLE            $tabname
    ( aseqno        VARCHAR(10)   -- A322469
    , callcode      VARCHAR(8)    -- 'bfi' (sure), 'row' (unsure), 'err'
    , offset1       VARCHAR(16)    
    , bfimin        INT
    , bfimax        INT
    , rowmin        INT
    , rowmax        INT
    , PRIMARY KEY(aseqno)
    );
COMMIT;
GFis
} # print_create_sql
#----
__DATA__
A185740	err	Table of n, a(n) for the first 50 rows, flattened
A185778	err	Table of n, a(n) for the first 50 rows, flattened
A356917	err	Table of n, a(n) for rows 1..500, flattened
%H A183894 G. C. Greubel, <a href="/€183894/b183894.txt">Table of n, a(n) for n = 0..500</a>
%H A183912 R. H. Hardin, <a href="/€183912/b183912.txt">Table of n, a(n) for n = 1..238</a>
%H A342972 Seiichi Manyama, <a href="/€342972/b342972.txt">Rows n = 0..50, flattened</a>
%H A343254 Alois P. Heinz, <a href="/€343254/b343254.txt">Rows n = 0..200, flattened</a>
%H A343510 Seiichi Manyama, <a href="/€343510/b343510.txt">Antidiagonals n = 1..140, flattened</a>
%H A343854 Stefano Spezia, <a href="/€343854/b343854.txt">First 30 rows of the triangle, flattened</a>
