#!perl

# Append a makefile extract at before the </body> tag
# @(#) $Id$
# 2026-07-05, Georg Fischer; *MH=78
#
#:# usage:
#:#   perl html_append.pl [-a $(TARGET).ext] $(TARGET).html
#:#       -a file to be appended (default: hmize.tmp)
#:#---------------------------------
use strict;
use integer;

my $append_name  = "hmize.tmp";
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A\-})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{a}) {
        $append_name =  shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

while (<>) {
    my $line = $_;
    if (0) {
    } elsif ($line =~ m{\A\<\/body\>}) {
        print "<pre>\n";
        open(APP, "<", $append_name) or die "cannot read \"$append_name\"\n";
        my $count = 0;
        while (<APP>) {
            my $append = $_;
            if ($append !~ m{\A\t}) { # does not start with tab
                $count ++;
                if ($count >= 2) {
                    last;
                }
            } else { # starts with tab
                # $append =~ s{\t}{}g;
                # keep the leading tab
                print $append; 
            }
        }
        close(APP);
        print "</pre>\n";
        print $line;
    } else {
        print $line;
    }
} # while <>
__DATA__
</table>
<p>
722 records
<br />Generated by <a href="https://github.com/gfis/joeis-lite/blob/master/internal/fischer/htmlize.pl">htmlize.pl</a>: 2026-07-04 21:38
<br />Questions, suggestions: email <a href="mailto:dr dot georg dot fischer at gmail dot com">Georg Fischer</a>
</p>
</body>
</html>

bern:
	grep -P "Bernoulli" jcat25.txt | grep -P "^%[NF]" | endirect \
	| cut -b 4- | perl -pe 's/ /\t/;' | tee    $@.tmp
	make hmize TARGET=$@
filprim:
	grep -P "Numbers [nk] such that \(\d+\^[^i]+is prime" joeis_names.txt | grep nyi | endirect \
	| cut -b 4- | perl -pe 's/ /\t/;' | tee    $@.tmp
	make hmize TARGET=$@
