--  OEIS-mat: lrindx - working table for index of linear recurrences
--  @(#) $Id$
--  2019-06-04 18:34:57, generated by extract_linrec.pl - DO NOT EDIT HERE!
--
DROP    TABLE  IF EXISTS lrindx;
CREATE  TABLE            lrindx
    ( lorder    INT         NOT NULL  -- order = number of right terms
    , compsig   VARCHAR(240)          -- blank separated, truncated, without "( )"
    , seqno     VARCHAR(8)  NOT NULL  -- 322469 without 'A'
    , sigorder  INT                   -- number of signature elements
    , signature VARCHAR(1020)         -- comma separated, without "( )"
    , comment   VARCHAR(1020)         -- behind signature, aseqno
    , PRIMARY KEY(lorder, compsig, seqno, sigorder)
    );
COMMIT;
