#!perl

# jocp.pl - Copy an existing jOEIS sequence into a new one
# @(#) $Id$
# 2026-04-17, Georg Fischer

#
#:# Usage:
#:#   perl jocp -a aseqno2 ../src/irvine/oeis/annn/aseqno1.java ../manual/aseqno2.java
#---------------------------------
use strict;
use integer;
use warnings;

my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d", $year + 1900, $mon + 1, $mday);
my $gits  =  $ENV{'GITS'};
my $names = "$gits/OEIS-mat/common/names";
my $debug = 0;
my $aseqno2 = "A000000";
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{a}) {
        $aseqno2   =  shift(@ARGV);
        #                  1   1 
        $aseqno2 =~ s{\A\W*(\d+)}{sprintf("A%06d", $1)}e;
    } elsif ($opt  =~ m{d}) {
        $debug     =  shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my $state = 0;
my $aseqno1 = "";
# while(<DATA>) {
while (<>) {
    s/\s+\Z//; # chompr
    my $line = $_;
    if (0) {
    } elsif($state == 0 && ($line =~ m{package irvine\.oeis\.(a\d+)})) {
        my $adir2 = lc(substr($aseqno2, 0, 4));
        $line =~ s{\.oeis\.(a\d+)}{\.oeis\.$adir2};
        print "$line\n";
        $state = 1;
    } elsif($state == 1) {
        if (0) {
        } elsif($line =~ m{^\/\/}) { # // Generated by ...
            $line = "// manually $timestamp";
            print "$line\n";
            $state = 2;
        } elsif($line =~ m{\A\s*\Z}) { # empty line
            print "\n";
        } elsif($line =~ m{^import}) { # import
            print "$line\n";
            $state = 2;
        } else { # ignore
        }
    } elsif($state == 2) { # sequence name comment
        if (0) {
        } elsif($line =~ m{^\s*\* (A\d{6}) }) {
            $aseqno1 = $1;
            my $name = `grep -P \"\^$aseqno2\" $names`; 
            $name =~ s{\A\s+}{}m;
            $name =~ s{\s+\Z}{}m;
            $name =~ s{\&}{\&amp\;}g;
            $name =~ s{\'}{\&ampos\;}g;
            $name =~ s{\<}{\&lt\;}g;
            $name =~ s{\>}{\&gt\;}g;
            $line = " * $name";
            print "$line\n";
            $state = 3;
        } elsif($line =~ m{\@author}) }) {
            $line = " * \@author Georg Fischer";
            print "$line\n";
        } else {
            $line =~ s{$aseqno1}{$aseqno2}g;
            print "$line\n";
        }
    } elsif($state == 3) { # rest of the source program
            $line =~ s{$aseqno1}{$aseqno2}g;
            print "$line\n";
    }
} # while <>
__DATA__
package irvine.oeis.a050;
// manually 2026-04-14

import irvine.math.z.Z;
import irvine.oeis.FiniteSequence;

/**
 * A050445 Each prime appears later in alphabetical order (in American English) than the one before.
 * @author Georg Fischer
 */
public class A050445 extends FiniteSequence {

  /** Construct the sequence. */
  public A050445() {
    super(1, FINITE, Z.TWO,
      Z.valueOf(211),
...