#!perl

# Prepare parameters for adjacent digits A126358 ff.
# @(#) $Id$
# 2021-10-05, Georg Fischer: copied from prep_pascal.pl
#
#:# Usage:
#:#   grep ... $(COMMON)/joeis_names.txt \
#:#   | perl adjacent.pl -d 0 > output.seq4
#--------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min);

my $debug = 0;
if (scalar(@ARGV) == 0) {
    print `grep -E "^#:#" $0 | cut -b3-`;
    exit;
}
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my %numbers = qw(zero 0 one 1 two 2 three 3 four 4 five 5 six 6 seven 7 eight 8 nine 9 ten 10 eleven 11 twelve 12);
print "# generated by combstruct/adjacent.pl $timestamp\n";
while (<>) {
    my $line = $_;
    $line =~ s{\s+\Z}{}; # chompr
    if ($line =~ m{\A(A\d+)}) {
        my ($aseqno, $superclass, $name, @rest) = split(/\t/, $line);
        $name =~ m{base +(\d+)};
        my $base = $1;
        $name =~ m{differing +by +(\w+)};
        my $diff = $numbers{$1} || "-1";
        if ($aseqno eq "A126501") {
            $diff =  4;
            $base = 6;
        }
        print join("\t", $aseqno, "parm3", "0", "A126358", $base, $diff, substr($name, 0, 64)) . "\n";
    }
} # while <>
#----------------
__DATA__
A126358	GeneratingFunctionSequence	Number of base 4 n-digit numbers with adjacent digits differing by one or less.	nonn,base,easy,changed,	1001
A126360	null	Number of base 6 n-digit numbers with adjacent digits differing by one or less.	nonn,base,changed,	2232
A126362	null	Number of base 8 n-digit numbers with adjacent digits differing by one or less.	nonn,base,changed,	2175
A126363	null	Number of base 9 n-digit numbers with adjacent digits differing by one or less.	nonn,base,synth	26
