#!perl

# Prepare parameters for WrapRecurrenceTriangles 
# @(#) $Id$
# 2021-10-06, Georg Fischer: copied from prep_pascal.pl
#
#:# Usage:
#:#   perl wraptr_prepare.pl [-2] input.seq4 > output.seq4
#:#        -2 force 2 border sequences
#--------------------------------------------------------
use strict;
use integer;
use warnings;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime (time);
my $timestamp = sprintf ("%04d-%02d-%02d %02d:%02d:%02d", $year + 1900, $mon + 1, $mday, $hour, $min, $sec);
print "# generated by trirec/wraptr_prepare.pl $timestamp\n";

my $force2 = 0; # may skip 2nd border sequence
my $debug = 0;
while (scalar(@ARGV) > 0 and ($ARGV[0] =~ m{\A[\-\+]})) {
    my $opt = shift(@ARGV);
    if (0) {
    } elsif ($opt  =~ m{d}) {
        $debug     = shift(@ARGV);
    } elsif ($opt  =~ m{2}) {
        $force2    = 1;
    } else {
        die "invalid option \"$opt\"\n";
    }
} # while $opt

my @parms;
my ($aseqno, $callcode, @rest);
my $sep = "~~";
my @skips = ("", "skipLeft", "skipRight", "skipPlus");
# while (<DATA>) {
while (<>) {
    my $line = $_;
    $line =~ s{\s+\Z}{}; # chompr
    if ($line =~ m{\A(A\d+)}) {
        $line =~ s{\t[\.\_]+}{\t}g; # remove "." and "_" used for indenting
        $line .= "\t\t\tdummy";
        ($aseqno, $callcode, $parms[0], $parms[1], $parms[2], $parms[3], $parms[4], @rest) = split(/\t/, $line, -1);
        my $skiplist = "";
        for (my $iparm = 1; $iparm <= 3; $iparm ++) {
            if ($parms[$iparm] =~ s{\_(\d+)}{}) {
                my $skip = $1;
                $skiplist .= "$sep$skips[$iparm]($skip);";
            }
            $parms[$iparm] =~ s{\A(A\d+)\Z}{new $1\(\)};
            $parms[$iparm] =~ s{\A([\-\d\,\|]+)\Z}{\"$1\"};
            if ($iparm == 3 && length($parms[$iparm]) > 0) {
                $parms[$iparm] = "~~setPlus($parms[$iparm]);"; 
            }
        } # for $iparm
        $parms[3] .= $skiplist;
        if (length($parms[3]) > 0) {
            $parms[3] = "$sep    $parms[3]";
        }
        $callcode = "wraptr2";
        if ($force2 == 0 and ($parms[1] eq $parms[2])) {
            $callcode = "wraptr1";
            $parms[2] = "";
        }
        print join("\t", $aseqno, $callcode, @parms) . "\n";
    }
} # while <>

#----------------
__DATA__
A053207	wraptr	0	A172273	A005843						Rows of triangle formed using Pascal's rule except begin n-th row with n and end it with n+1.
A054143	wraptr	0	______1	A168604						Triangular array T given by T(n,k) = Sum_{0 <= j <= i-n+k, n-k <= i <= n} C(i,j) for n >= 0 and 0 <= k <= n.
A057211	wraptr	1	A059841	A059841_3	A059841	~~    ~~return getPlus();					n-th run has length n.
A316939	wraptr	0	A000045_2	A000045_2						Triangle read by rows formed using Pascal's rule except that n-th row begins and ends with Fibonacci(n+2).
